[WIP]database_design
major238/chat-space pull request #1
Opened 2019-04-14 07:52 UTC by major238

# What
チャットスペースデータベース設計のレビュー願い

# Why
きちんと設計できているか不安なため。

2019-04-14 08:07 UTC, yuki-uchida requested changes

2019-04-14 08:07 UTC, yuki-uchida commented on README.md
> +|user_id|integer|null: false, foreign_key: true|
外部キーの場合にはreferences型としましょう

2019-04-14 08:07 UTC, yuki-uchida commented on README.md
> +|groupname|string|null: false,length: { maximum: 15}|
nameで良いです

2019-04-14 08:07 UTC, yuki-uchida commented on README.md
> +|tweet|text|null: false,length: { maximum: 125}|
画像を投稿したいです

2019-04-15 12:34 UTC, major238 commented on README.md
> +|user_id|integer|null: false, foreign_key: true|
全て外部キーとしているものはreference型にしないといけないのでしょうか？
indexを付与することが不要なようなので、今回は全てreference型としました。
逆にindexを使いたく無いときはint型で定義すればよろしいのでしょうか？

2019-04-15 12:35 UTC, major238 commented on README.md
> +|groupname|string|null: false,length: { maximum: 15}|
nameとしました。

2019-04-15 12:44 UTC, major238 commented on README.md
> +|tweet|text|null: false,length: { maximum: 125}|
imageカラムを作成しました。

2019-04-15 12:56 UTC, TOMARUMARU commented on README.md
> +|handle_name|string|null: false, length: { maximum: 15}|
nameで大丈夫です
length: { maximum: 15}の記述は不要です
indexとuniqueをつけましょう

2019-04-15 12:56 UTC, TOMARUMARU commented on README.md
> +|tweet|reference|null: false, foreign_key: true|
こちらは不要です

2019-04-15 12:56 UTC, TOMARUMARU commented on README.md
> +|group|reference|null: false, foreign_key: true|
中間テーブルで管理するので不要です

2019-04-15 12:56 UTC, TOMARUMARU commented on README.md
> +|tweet|text|null: false,length: { maximum: 125}|
画像単体で送れなくなるのでnullは許容しましょう
length: { maximum: 125}不要です

2019-04-15 12:56 UTC, TOMARUMARU commented on README.md
> +|timestamp|timestamp|null: false|
created_atを使えば不要です

2019-04-15 12:56 UTC, TOMARUMARU commented on README.md
> +|image|string|null: true|
こちらもnullを許容してください

2019-04-15 12:56 UTC, TOMARUMARU commented on README.md
> +|name|string|null: false,length: { maximum: 15}|
length: { maximum: 15}不要です

2019-04-15 12:56 UTC, TOMARUMARU commented on README.md
> +|user|reference|null: false, foreign_key: true|
中間テーブルで管理します

2019-04-15 12:56 UTC, TOMARUMARU commented on README.md
> +|tweet|reference|null: false, foreign_key: true|
不要です

2019-04-15 12:56 UTC, TOMARUMARU reviewed
アソシエーションがしっかり組めていません。
usersとgroupsが中間テーブル(members)を用いて多対多になるので今一度調べて修正をお願いします

2019-04-15 13:24 UTC, major238 commented on README.md
> +|tweet|text|null: false,length: { maximum: 125}|
修正しました。
確かに画像のみ送信を考慮に入れておりませんでした。

2019-04-15 13:25 UTC, major238 commented on README.md
> +|image|string|null: true|
imageはnull:trueとしています。
tweetのことでしょうか？

2019-04-15 13:25 UTC, major238 commented on README.md
> +|name|string|null: false,length: { maximum: 15}|
修正しました。

2019-04-22 10:19 UTC, major238 commented on README.md
> +|timestamp|timestamp|null: false|
修正しました

2019-04-22 10:28 UTC, major238 commented on README.md
> +|handle_name|string|null: false, length: { maximum: 15}|
修正しました

2019-04-22 10:28 UTC, major238 commented on README.md
> +|group|reference|null: false, foreign_key: true|
削除しました

2019-04-22 10:39 UTC, major238 commented on README.md
> +|tweet|reference|null: false, foreign_key: true|
削除しました。
tweetsテーブルだけに残し１対多の関係だけ維持しております。他のテーブルに関しては中間テーブルを経由しました。

2019-04-22 10:50 UTC, major238 commented on README.md
> +|user|reference|null: false, foreign_key: true|
修正しました

2019-04-22 10:56 UTC, TOMARUMARU commented
https://qiita.com/Kohei_Kishimoto0214/items/cb9a3d3da57708fb52c9

こちらに記事を参考にもう一度アソシエーションを見直してください

2019-04-22 11:29 UTC, major238 commented
> https://qiita.com/Kohei_Kishimoto0214/items/cb9a3d3da57708fb52c9
> 
> こちらに記事を参考にもう一度アソシエーションを見直してください

2019-04-22 11:32 UTC, TOMARUMARU reviewed
PRがcloseされてるのでreopenしてください

2019-04-22 11:32 UTC, TOMARUMARU commented on README.md
> +|name|string|null: false,unique: true,add_index :users,  :name|
index: trueとしましょう

2019-04-22 11:32 UTC, TOMARUMARU commented on README.md
> +- has_many :groups, through: :members
別途membersと組む必要があります

2019-04-22 11:32 UTC, TOMARUMARU commented on README.md
> +|tweet|text|null: true|
content等のカラム名が適切です。null許容はdefaultなので記述しなくて大丈夫です

2019-04-22 11:32 UTC, TOMARUMARU commented on README.md
> +|created_at|timestamp|null: false|
自動生成されます

2019-04-22 11:32 UTC, TOMARUMARU commented on README.md
> +|image|string|null: true|
null許容はdefaultなので記述しなくて大丈夫です

2019-04-22 11:32 UTC, TOMARUMARU commented on README.md
> +- has_many :users, through: :members
別途membersと組む必要があります

2019-04-22 11:32 UTC, major238 commented
GroupsとUsersが他対他の関係
TweetとGroup、Userhaそれぞれ１対他の関係だと考えております。
そのためTweetsテーブル内で参照先のUser及びGroupテーブルを参照しているつもりなんですがそこから間違えているのでしょうか。

2019-04-22 11:42 UTC, major238 commented on README.md
> +|image|string|null: true|
修正しました

2019-04-22 11:42 UTC, major238 commented on README.md
> +|created_at|timestamp|null: false|
削除しました

2019-04-22 11:42 UTC, major238 commented on README.md
> +|tweet|text|null: true|
修正しました。

2019-04-22 11:44 UTC, major238 commented on README.md
> +|name|string|null: false,unique: true,add_index :users,  :name|
修正しました。

2019-04-22 11:46 UTC, major238 commented on README.md
> +- has_many :users, through: :members
class Group < ApplicationRecord
    has_many :users, through: :group_users
    has_many :group_users
記事のようにthrough先のテーブルを組む必要があるんですね。修正しました。

2019-04-22 11:49 UTC, major238 commented on README.md
> +- has_many :groups, through: :members
組みました。ようやく理解しました。ありがとうございます。

2019-04-22 11:56 UTC, TOMARUMARU approved these changes
LGTMです、お疲れ様でした!

細かいですがreferenceとなっているところはreferencesです！
修正したらmergeしていただいて大丈夫です

2019-04-22 12:00 UTC, merged